name: tests
on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        cache: 'npm'
    - run: npm ci
    - run: "echo skipped-for-baseline-isolation"
    - run: npx eslint --config .eslintrc.json --ignore-path .eslintignore extension/data/tbcore.js extension/data/tbui.js extension/data/modules/config.js
    - run: "echo skipped-for-baseline-isolation"
